import { User, Court, Match, Transaction } from "@/entities/types";

const uuid = (id: number) => `00000000-0000-0000-0000-${id.toString().padStart(12, "0")}`;
const isoNow = new Date().toISOString();
const futureDay = (days: number) => new Date(Date.now() + days * 86400000).toISOString();

export const MOCK_USERS: User[] = [
  {
    id: "user-edwin-master",
    created_at: isoNow,
    name: "Edwin Flores",
    age: 29,
    city: "Surco",
    avatar_url: "https://i.pravatar.cc/150?u=edwin",
    bio: "Usuario Maestro Edwin.",
    trust_score: 99,
    matches_played: 15,
    fitcoins_balance: 3500,
    level: "Elite",
    preferred_sports: ["Pádel", "Fútbol"],
    last_location_lat: -12.14,
    last_location_lng: -76.995,
    email: "ejuniorfloress@gmail.com",
    password: "EdwinFlores123?",
    user_role: "PLAYER",
  },
  {
    id: "user-puka-power",
    created_at: isoNow,
    name: "Puka Power",
    age: 5,
    city: "Surco",
    avatar_url: "https://api.dicebear.com/7.x/identicon/svg?seed=PukaPower",
    bio: "Puka Power Oficial - Energizante Premium. ⚡🔋 Recarga tus energías y canjea tus bebidas.",
    trust_score: 100,
    matches_played: 0,
    fitcoins_balance: 100000,
    level: "Elite",
    preferred_sports: [],
    last_location_lat: -12.135,
    last_location_lng: -76.99,
    email: "puka@puka.com",
    password: "Puka123?",
    user_role: "BUSINESS",
    company_name: "Puka Power S.A.C.",
    business_category: "Bebidas",
    is_sponsored: true,
  },
  {
    id: "user-fabiola",
    created_at: isoNow,
    name: "Fabiola",
    age: 26,
    city: "Surco",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fabiola",
    bio: "Buscando partidos de tenis y pádel.",
    trust_score: 95,
    matches_played: 8,
    fitcoins_balance: 1200,
    level: "Intermedio",
    preferred_sports: ["Pádel", "Tenis"],
    last_location_lat: -12.13,
    last_location_lng: -76.98,
    email: "fabiola@sportmatch.app",
    password: "Fabiola123?",
  },
  {
    id: uuid(1),
    created_at: isoNow,
    name: "Alex Rivera",
    age: 27,
    city: "Surco",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    bio: "Amante del Pádel. Juego siempre que puedo.",
    trust_score: 93,
    matches_played: 12,
    fitcoins_balance: 1850,
    level: "Avanzado",
    preferred_sports: ["Pádel", "Fútbol"],
    last_location_lat: -12.1189,
    last_location_lng: -76.995,
  },
  {
    id: uuid(2),
    created_at: isoNow,
    name: "Camila Torres",
    age: 24,
    city: "Miraflores",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Camila",
    bio: "Compito en torneos los fines de semana.",
    trust_score: 96,
    matches_played: 12,
    fitcoins_balance: 1240,
    level: "Avanzado",
    preferred_sports: ["Pádel"],
    last_location_lat: -12.1221,
    last_location_lng: -77.0298,
    distance_km: 1.2,
  },
  {
    id: uuid(3),
    created_at: isoNow,
    name: "Diego Ramírez",
    age: 28,
    city: "San Borja",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Diego",
    bio: "Mediocampista. Juego martes y jueves.",
    trust_score: 88,
    matches_played: 12,
    fitcoins_balance: 860,
    level: "Intermedio",
    preferred_sports: ["Fútbol"],
    last_location_lat: -12.1084,
    last_location_lng: -76.9981,
    distance_km: 2.4,
  },
  {
    id: uuid(4),
    created_at: isoNow,
    name: "Sofia Silva",
    age: 31,
    city: "Surco",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia",
    bio: "Crossfit y Running. Empujando límites.",
    trust_score: 99,
    matches_played: 12,
    fitcoins_balance: 3200,
    level: "Avanzado",
    preferred_sports: ["Running"],
    last_location_lat: -12.115,
    last_location_lng: -76.98,
    distance_km: 0.8,
  },
  {
    id: uuid(5),
    created_at: isoNow,
    name: "Mateo Ortiz",
    age: 22,
    city: "Barranco",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mateo",
    bio: "Futbol y amigos.",
    trust_score: 82,
    matches_played: 12,
    fitcoins_balance: 450,
    level: "Principiante",
    preferred_sports: ["Fútbol"],
    last_location_lat: -12.14,
    last_location_lng: -77.02,
    distance_km: 3.5,
  },
  {
    id: uuid(6),
    created_at: isoNow,
    name: "Valentina Vega",
    age: 26,
    city: "Miraflores",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Valentina",
    bio: "Buscando dupla de pádel femenino.",
    trust_score: 95,
    matches_played: 12,
    fitcoins_balance: 1100,
    level: "Intermedio",
    preferred_sports: ["Pádel"],
    last_location_lat: -12.128,
    last_location_lng: -77.035,
    distance_km: 1.5,
  },
  {
    id: uuid(7),
    created_at: isoNow,
    name: "Lucas Castro",
    age: 29,
    city: "San Isidro",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
    bio: "Tenis de polvo de ladrillo.",
    trust_score: 91,
    matches_played: 12,
    fitcoins_balance: 2100,
    level: "Avanzado",
    preferred_sports: ["Tenis"],
    last_location_lat: -12.095,
    last_location_lng: -77.03,
    distance_km: 4.1,
  },
  {
    id: uuid(8),
    created_at: isoNow,
    name: "Elena Ramos",
    age: 33,
    city: "San Borja",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Elena",
    bio: "Yoga y Pilates.",
    trust_score: 98,
    matches_played: 12,
    fitcoins_balance: 400,
    level: "Intermedio",
    preferred_sports: ["Running"],
    last_location_lat: -12.1,
    last_location_lng: -77.0,
    distance_km: 2.1,
  },
  {
    id: uuid(9),
    created_at: isoNow,
    name: "Martin Luna",
    age: 25,
    city: "Surco",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Martin",
    bio: "Defensa central duro pero limpio.",
    trust_score: 85,
    matches_played: 12,
    fitcoins_balance: 600,
    level: "Avanzado",
    preferred_sports: ["Fútbol"],
    last_location_lat: -12.13,
    last_location_lng: -76.99,
    distance_km: 1.1,
  },
  {
    id: uuid(10),
    created_at: isoNow,
    name: "Julia Soto",
    age: 27,
    city: "Miraflores",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Julia",
    bio: "Revés a dos manos.",
    trust_score: 92,
    matches_played: 12,
    fitcoins_balance: 1550,
    level: "Intermedio",
    preferred_sports: ["Tenis"],
    last_location_lat: -12.12,
    last_location_lng: -77.025,
    distance_km: 1.8,
  },
];

export const MOCK_COURTS: Court[] = [
  {
    id: uuid(101),
    created_at: isoNow,
    name: "Pádel Center Surco",
    sport: "Pádel",
    price_per_hour: 40,
    rating: 4.8,
    reviews_count: 312,
    lat: -12.145,
    lng: -77.0,
    image_url: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8",
    amenities: ["Iluminación", "Vestuarios", "Parking", "Cafetería"],
    is_available: true,
    distance_km: 0.6,
  },
  {
    id: uuid(102),
    created_at: isoNow,
    name: "Complejo Deportivo Jorge Chávez",
    sport: "Fútbol",
    price_per_hour: 120,
    rating: 4.6,
    reviews_count: 480,
    lat: -12.155,
    lng: -77.005,
    image_url: "https://images.unsplash.com/photo-1551958219-acbc608c6377",
    amenities: ["Pasto sintético", "Gradas", "Duchas"],
    is_available: true,
    distance_km: 1.4,
  },
  {
    id: uuid(103),
    created_at: isoNow,
    name: "Tenis Club San Borja",
    sport: "Tenis",
    price_per_hour: 35,
    rating: 4.9,
    reviews_count: 150,
    lat: -12.1,
    lng: -76.99,
    image_url: "https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0",
    amenities: ["Polvo de ladrillo", "Árbitro"],
    is_available: false,
    distance_km: 2.2,
  },
  {
    id: uuid(104),
    created_at: isoNow,
    name: "Pádel Rooftop Jockey",
    sport: "Pádel",
    price_per_hour: 55,
    rating: 4.7,
    reviews_count: 220,
    lat: -12.085,
    lng: -76.975,
    image_url: "https://images.unsplash.com/photo-1622279457486-62dcc4a631d6",
    amenities: ["Vista panorámica", "Alquiler de paletas"],
    is_available: true,
    distance_km: 3.8,
  },
  {
    id: uuid(105),
    created_at: isoNow,
    name: "Polideportivo Limatambo",
    sport: "Fútbol",
    price_per_hour: 80,
    rating: 4.3,
    reviews_count: 512,
    lat: -12.109,
    lng: -77.012,
    image_url: "https://images.unsplash.com/photo-1518605368461-1ee7e5302a40",
    amenities: ["Fútbol 7", "Kiosko"],
    is_available: true,
    distance_km: 1.9,
  },
];

export const MOCK_MATCHES: Match[] = [
  {
    id: uuid(211),
    created_at: isoNow,
    creator_id: "user-edwin-master",
    court_id: uuid(101),
    sport: "Pádel",
    title: "Pádel Edwin Masterclass",
    date: futureDay(1).split("T")[0],
    time: "20:00",
    max_players: 4,
    required_level: "Elite",
    court: MOCK_COURTS[0],
    current_players: [MOCK_USERS[0], MOCK_USERS[1]],
  },
  {
    id: uuid(212),
    created_at: isoNow,
    creator_id: "user-edwin-master",
    court_id: uuid(102),
    sport: "Fútbol",
    title: "Fútbol 7 con Edwin",
    date: futureDay(2).split("T")[0],
    time: "21:00",
    max_players: 14,
    required_level: "Avanzado",
    court: MOCK_COURTS[1],
    current_players: [MOCK_USERS[0], MOCK_USERS[2], MOCK_USERS[3]],
  },
  {
    id: uuid(201),
    created_at: isoNow,
    creator_id: uuid(1),
    court_id: uuid(101),
    sport: "Pádel",
    title: "Doble Mixto Semipro",
    date: futureDay(1).split("T")[0],
    time: "18:00",
    max_players: 4,
    required_level: "Avanzado",
    court: MOCK_COURTS[0],
    current_players: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[5]],
  },
  {
    id: uuid(202),
    created_at: isoNow,
    creator_id: uuid(3),
    court_id: uuid(102),
    sport: "Fútbol",
    title: "Pichanga Jueves Noche",
    date: futureDay(2).split("T")[0],
    time: "18:00",
    max_players: 14,
    required_level: "Intermedio",
    court: MOCK_COURTS[1],
    current_players: [MOCK_USERS[2], MOCK_USERS[4], MOCK_USERS[8]],
  },
  {
    id: uuid(203),
    created_at: isoNow,
    creator_id: uuid(7),
    court_id: uuid(103),
    sport: "Tenis",
    title: "Singles Práctica",
    date: futureDay(0.5).split("T")[0],
    time: "18:00",
    max_players: 2,
    required_level: "Avanzado",
    court: MOCK_COURTS[2],
    current_players: [MOCK_USERS[6]],
  },
  {
    id: uuid(204),
    created_at: isoNow,
    creator_id: uuid(6),
    court_id: uuid(101),
    sport: "Pádel",
    title: "Pádel Femenino Relax",
    date: futureDay(3).split("T")[0],
    time: "18:00",
    max_players: 4,
    required_level: "Intermedio",
    court: MOCK_COURTS[0],
    current_players: [MOCK_USERS[5]],
  },
  {
    id: uuid(205),
    created_at: isoNow,
    creator_id: uuid(9),
    court_id: uuid(105),
    sport: "Fútbol",
    title: "Fútbol 7 - San Borja",
    date: futureDay(1.5).split("T")[0],
    time: "18:00",
    max_players: 14,
    required_level: "Avanzado",
    court: MOCK_COURTS[4],
    current_players: [MOCK_USERS[8], MOCK_USERS[2]],
  },
  {
    id: uuid(206),
    created_at: isoNow,
    creator_id: uuid(10),
    court_id: uuid(103),
    sport: "Tenis",
    title: "Dobles Mixtos",
    date: futureDay(4).split("T")[0],
    time: "18:00",
    max_players: 4,
    required_level: "Intermedio",
    court: MOCK_COURTS[2],
    current_players: [MOCK_USERS[9], MOCK_USERS[6]],
  },
  {
    id: uuid(207),
    created_at: isoNow,
    creator_id: uuid(4),
    court_id: uuid(102),
    sport: "Fútbol",
    title: "Entrenamiento Funcional / Fútbol",
    date: futureDay(0.2).split("T")[0],
    time: "18:00",
    max_players: 10,
    required_level: "Avanzado",
    court: MOCK_COURTS[1],
    current_players: [MOCK_USERS[3], MOCK_USERS[4]],
  },
  {
    id: uuid(208),
    created_at: isoNow,
    creator_id: uuid(1),
    court_id: uuid(104),
    sport: "Pádel",
    title: "Torneo Interno Rooftop",
    date: futureDay(5).split("T")[0],
    time: "18:00",
    max_players: 4,
    required_level: "Avanzado",
    court: MOCK_COURTS[3],
    current_players: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[5], MOCK_USERS[6]],
  },
  {
    id: uuid(209),
    created_at: isoNow,
    creator_id: uuid(2),
    court_id: uuid(101),
    sport: "Pádel",
    title: "Práctica Saques",
    date: futureDay(6).split("T")[0],
    time: "18:00",
    max_players: 2,
    required_level: "Intermedio",
    court: MOCK_COURTS[0],
    current_players: [MOCK_USERS[1]],
  },
  {
    id: uuid(210),
    created_at: isoNow,
    creator_id: uuid(8),
    court_id: uuid(105),
    sport: "Running",
    title: "Trote Grupal Parque Sur",
    date: futureDay(0.1).split("T")[0],
    time: "18:00",
    max_players: 20,
    required_level: "Principiante",
    court: MOCK_COURTS[4],
    current_players: [MOCK_USERS[7], MOCK_USERS[3]],
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: uuid(305),
    created_at: isoNow,
    user_id: "user-edwin-master",
    amount: 500,
    description: "Bono de bienvenida",
    type: "EARN",
  },
  {
    id: uuid(306),
    created_at: isoNow,
    user_id: "user-edwin-master",
    amount: 150,
    description: "Reto completado: 3 Partidos de Tenis",
    type: "EARN",
  },
  {
    id: uuid(307),
    created_at: isoNow,
    user_id: "user-edwin-master",
    amount: -100,
    description: "Canje: Bebida isotónica",
    type: "SPEND",
  },
  {
    id: uuid(301),
    created_at: isoNow,
    user_id: uuid(1),
    amount: 150,
    description: "Reto semanal completado",
    type: "EARN",
  },
  {
    id: uuid(302),
    created_at: isoNow,
    user_id: uuid(1),
    amount: -500,
    description: "Canje: Hora gratis de Pádel",
    type: "SPEND",
  },
  {
    id: uuid(303),
    created_at: isoNow,
    user_id: uuid(1),
    amount: 50,
    description: "Puntualidad en partido",
    type: "EARN",
  },
  {
    id: uuid(304),
    created_at: isoNow,
    user_id: uuid(1),
    amount: 200,
    description: "MVP del partido",
    type: "EARN",
  },
];

// Current session user (Mock Auth)
export const ME = MOCK_USERS[0];

export const SPORTS = [
  { name: "Pádel", emoji: "🎾" },
  { name: "Fútbol", emoji: "⚽" },
  { name: "Tenis", emoji: "🎾" },
  { name: "Running", emoji: "🏃" },
];

export const LEADERBOARD = MOCK_USERS.map((u, i) => ({
  rank: i + 1,
  name: u.name,
  avatar: u.avatar_url,
  coins: u.fitcoins_balance,
}))
  .sort((a, b) => b.coins - a.coins)
  .map((u, i) => ({ ...u, rank: i + 1 }));

export type Message = {
  id: string;
  sender_id: string;
  text: string;
  created_at: string;
};

export type Chat = {
  id: string;
  name: string;
  avatar: string;
  current_players: string[];
  messages: Message[];
  unread: number;
};

export const MOCK_CHATS: Chat[] = [
  {
    id: "chat_group_pichanga",
    name: "Pichanga Jueves",
    avatar: "https://api.dicebear.com/7.x/shapes/svg?seed=PichangaGroup",
    current_players: ["user-edwin-master", "user-fabiola", uuid(3)],
    unread: 1,
    messages: [
      {
        id: "msg_group_1",
        sender_id: uuid(3),
        text: "Confirmen quiénes van este jueves para separar la cancha ⚽",
        created_at: new Date(Date.now() - 3600000).toISOString(),
      },
      {
        id: "msg_group_2",
        sender_id: "user-edwin-master",
        text: "¡Yo me apunto! Llevo las pelotas oficiales.",
        created_at: new Date(Date.now() - 3000000).toISOString(),
      },
      {
        id: "msg_group_3",
        sender_id: "user-fabiola",
        text: "¿Quién lleva la pelota?",
        created_at: new Date(Date.now() - 1000000).toISOString(),
      },
    ],
  },
  {
    id: "chat_fabiola",
    name: "Fabiola",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fabiola",
    current_players: ["user-edwin-master", "user-fabiola"],
    unread: 0,
    messages: [
      {
        id: "msg_fab_1",
        sender_id: "user-fabiola",
        text: "Hola Edwin, ¿jugamos un partido de pádel mañana?",
        created_at: new Date(Date.now() - 86400000).toISOString(),
      },
      {
        id: "msg_fab_2",
        sender_id: "user-edwin-master",
        text: "¡Hola! Claro que sí, a qué hora puedes?",
        created_at: new Date(Date.now() - 82800000).toISOString(),
      },
      {
        id: "msg_fab_3",
        sender_id: "user-edwin-master",
        text: "¡Amor, ya separé la cancha para hoy a las 8pm! 🎾",
        created_at: new Date(Date.now() - 1000000).toISOString(),
      },
    ],
  },
  {
    id: "chat_1",
    name: "Grupo Pádel Jueves",
    avatar: "https://api.dicebear.com/7.x/shapes/svg?seed=PadelGroup",
    current_players: ["user-edwin-master", uuid(2), uuid(5)],
    unread: 2,
    messages: [
      {
        id: "msg_1",
        sender_id: uuid(2),
        text: "¿Alguien tiene paleta extra? La mía se rompió ayer 😭",
        created_at: new Date(Date.now() - 3600000).toISOString(),
      },
      {
        id: "msg_2",
        sender_id: "user-edwin-master",
        text: "Tranqui, yo llevo dos. ¡Nos vemos 19hs en Club Central!",
        created_at: new Date(Date.now() - 3000000).toISOString(),
      },
    ],
  },
  {
    id: "chat_2",
    name: "Camila Torres",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Camila",
    current_players: ["user-edwin-master", uuid(2)],
    unread: 0,
    messages: [
      {
        id: "msg_3",
        sender_id: uuid(2),
        text: "¡Buen partido ayer Edwin! A ver cuándo repetimos.",
        created_at: new Date(Date.now() - 86400000).toISOString(),
      },
      {
        id: "msg_4",
        sender_id: "user-edwin-master",
        text: "¡Estuvo buenísimo! El próximo martes te aviso si armamos otro.",
        created_at: new Date(Date.now() - 82800000).toISOString(),
      },
    ],
  },
];

// Load dynamically registered users from localStorage on module initialization
if (typeof window !== "undefined") {
  const registeredRaw = localStorage.getItem("sportmatch-registered-users");
  if (registeredRaw) {
    try {
      const registeredList = JSON.parse(registeredRaw);
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      registeredList.forEach((u: any) => {
        if (!MOCK_USERS.some((existing) => existing.id === u.id)) {
          MOCK_USERS.push(u);
        }
      });
    } catch (e) {
      console.error("Failed to parse registered mock users:", e);
    }
  }
}

// Sync current mock users back to storage
export function syncMockUsersToStorage() {
  if (typeof window !== "undefined") {
    const dynamicUsers = MOCK_USERS.filter(
      (u) =>
        u.id !== "user-edwin-master" &&
        u.id !== "user-fabiola" &&
        u.id !== "user-puka-power" &&
        !u.id.startsWith("00000000-0000-0000-0000-"),
    );
    localStorage.setItem("sportmatch-registered-users", JSON.stringify(dynamicUsers));
  }
}
