[build]
builder = "NIXPACKS"
buildCommand = "cd /app/server && npm install && npx prisma generate && npm run build"
startCommand = "cd /app/server && npm start"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10