/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRegisterRouteImport } from './routes/app.register'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMatchRouteImport } from './routes/app.match'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppIotRouteImport } from './routes/app.iot'
import { Route as AppCourtsRouteImport } from './routes/app.courts'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppBusinessRouteImport } from './routes/app.business'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppWalletIndexRouteImport } from './routes/app.wallet.index'
import { Route as AppMatchIndexRouteImport } from './routes/app.match.index'
import { Route as AppWalletHistoryRouteImport } from './routes/app.wallet.history'
import { Route as AppMatchUserIdRouteImport } from './routes/app.match.$userId'
import { Route as AppCourtsCourtIdRouteImport } from './routes/app.courts.$courtId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchRoute = AppMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppIotRoute = AppIotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => AppRoute,
} as any)
const AppCourtsRoute = AppCourtsRouteImport.update({
  id: '/courts',
  path: '/courts',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessRoute = AppBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletIndexRoute = AppWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchIndexRoute = AppMatchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMatchRoute,
} as any)
const AppWalletHistoryRoute = AppWalletHistoryRouteImport.update({
  id: '/wallet/history',
  path: '/wallet/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchUserIdRoute = AppMatchUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppMatchRoute,
} as any)
const AppCourtsCourtIdRoute = AppCourtsCourtIdRouteImport.update({
  id: '/$courtId',
  path: '/$courtId',
  getParentRoute: () => AppCourtsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/business': typeof AppBusinessRoute
  '/app/chat': typeof AppChatRoute
  '/app/courts': typeof AppCourtsRouteWithChildren
  '/app/iot': typeof AppIotRoute
  '/app/map': typeof AppMapRoute
  '/app/match': typeof AppMatchRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/register': typeof AppRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/courts/$courtId': typeof AppCourtsCourtIdRoute
  '/app/match/$userId': typeof AppMatchUserIdRoute
  '/app/wallet/history': typeof AppWalletHistoryRoute
  '/app/match/': typeof AppMatchIndexRoute
  '/app/wallet/': typeof AppWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/business': typeof AppBusinessRoute
  '/app/chat': typeof AppChatRoute
  '/app/courts': typeof AppCourtsRouteWithChildren
  '/app/iot': typeof AppIotRoute
  '/app/map': typeof AppMapRoute
  '/app/profile': typeof AppProfileRoute
  '/app/register': typeof AppRegisterRoute
  '/app': typeof AppIndexRoute
  '/app/courts/$courtId': typeof AppCourtsCourtIdRoute
  '/app/match/$userId': typeof AppMatchUserIdRoute
  '/app/wallet/history': typeof AppWalletHistoryRoute
  '/app/match': typeof AppMatchIndexRoute
  '/app/wallet': typeof AppWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/business': typeof AppBusinessRoute
  '/app/chat': typeof AppChatRoute
  '/app/courts': typeof AppCourtsRouteWithChildren
  '/app/iot': typeof AppIotRoute
  '/app/map': typeof AppMapRoute
  '/app/match': typeof AppMatchRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/register': typeof AppRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/courts/$courtId': typeof AppCourtsCourtIdRoute
  '/app/match/$userId': typeof AppMatchUserIdRoute
  '/app/wallet/history': typeof AppWalletHistoryRoute
  '/app/match/': typeof AppMatchIndexRoute
  '/app/wallet/': typeof AppWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/business'
    | '/app/chat'
    | '/app/courts'
    | '/app/iot'
    | '/app/map'
    | '/app/match'
    | '/app/profile'
    | '/app/register'
    | '/app/'
    | '/app/courts/$courtId'
    | '/app/match/$userId'
    | '/app/wallet/history'
    | '/app/match/'
    | '/app/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/admin'
    | '/app/business'
    | '/app/chat'
    | '/app/courts'
    | '/app/iot'
    | '/app/map'
    | '/app/profile'
    | '/app/register'
    | '/app'
    | '/app/courts/$courtId'
    | '/app/match/$userId'
    | '/app/wallet/history'
    | '/app/match'
    | '/app/wallet'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/business'
    | '/app/chat'
    | '/app/courts'
    | '/app/iot'
    | '/app/map'
    | '/app/match'
    | '/app/profile'
    | '/app/register'
    | '/app/'
    | '/app/courts/$courtId'
    | '/app/match/$userId'
    | '/app/wallet/history'
    | '/app/match/'
    | '/app/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/register': {
      id: '/app/register'
      path: '/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/match': {
      id: '/app/match'
      path: '/match'
      fullPath: '/app/match'
      preLoaderRoute: typeof AppMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/iot': {
      id: '/app/iot'
      path: '/iot'
      fullPath: '/app/iot'
      preLoaderRoute: typeof AppIotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courts': {
      id: '/app/courts'
      path: '/courts'
      fullPath: '/app/courts'
      preLoaderRoute: typeof AppCourtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/business': {
      id: '/app/business'
      path: '/business'
      fullPath: '/app/business'
      preLoaderRoute: typeof AppBusinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/': {
      id: '/app/wallet/'
      path: '/wallet'
      fullPath: '/app/wallet/'
      preLoaderRoute: typeof AppWalletIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/match/': {
      id: '/app/match/'
      path: '/'
      fullPath: '/app/match/'
      preLoaderRoute: typeof AppMatchIndexRouteImport
      parentRoute: typeof AppMatchRoute
    }
    '/app/wallet/history': {
      id: '/app/wallet/history'
      path: '/wallet/history'
      fullPath: '/app/wallet/history'
      preLoaderRoute: typeof AppWalletHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/match/$userId': {
      id: '/app/match/$userId'
      path: '/$userId'
      fullPath: '/app/match/$userId'
      preLoaderRoute: typeof AppMatchUserIdRouteImport
      parentRoute: typeof AppMatchRoute
    }
    '/app/courts/$courtId': {
      id: '/app/courts/$courtId'
      path: '/$courtId'
      fullPath: '/app/courts/$courtId'
      preLoaderRoute: typeof AppCourtsCourtIdRouteImport
      parentRoute: typeof AppCourtsRoute
    }
  }
}

interface AppCourtsRouteChildren {
  AppCourtsCourtIdRoute: typeof AppCourtsCourtIdRoute
}

const AppCourtsRouteChildren: AppCourtsRouteChildren = {
  AppCourtsCourtIdRoute: AppCourtsCourtIdRoute,
}

const AppCourtsRouteWithChildren = AppCourtsRoute._addFileChildren(
  AppCourtsRouteChildren,
)

interface AppMatchRouteChildren {
  AppMatchUserIdRoute: typeof AppMatchUserIdRoute
  AppMatchIndexRoute: typeof AppMatchIndexRoute
}

const AppMatchRouteChildren: AppMatchRouteChildren = {
  AppMatchUserIdRoute: AppMatchUserIdRoute,
  AppMatchIndexRoute: AppMatchIndexRoute,
}

const AppMatchRouteWithChildren = AppMatchRoute._addFileChildren(
  AppMatchRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBusinessRoute: typeof AppBusinessRoute
  AppChatRoute: typeof AppChatRoute
  AppCourtsRoute: typeof AppCourtsRouteWithChildren
  AppIotRoute: typeof AppIotRoute
  AppMapRoute: typeof AppMapRoute
  AppMatchRoute: typeof AppMatchRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWalletHistoryRoute: typeof AppWalletHistoryRoute
  AppWalletIndexRoute: typeof AppWalletIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBusinessRoute: AppBusinessRoute,
  AppChatRoute: AppChatRoute,
  AppCourtsRoute: AppCourtsRouteWithChildren,
  AppIotRoute: AppIotRoute,
  AppMapRoute: AppMapRoute,
  AppMatchRoute: AppMatchRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppIndexRoute: AppIndexRoute,
  AppWalletHistoryRoute: AppWalletHistoryRoute,
  AppWalletIndexRoute: AppWalletIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
